Personal_Blog/urls.py
#Django
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('posts.urls','posts'), namespace = 'posts')),
    path('users/',include(('users.urls','users'), namespace = 'users')),
]

posts/urls.py
"""Posts URLS.s"""

#Django
from django.urls import path

#views
from posts import views

urlpatterns = [

    # Management
    path(
        route='',
        view=views.WelcomeView.as_view(),
        name='welcome'
    ),
    path(
        route='feed/',
        view=views.FeedView.as_view(),
        name='feed'
    ),

    path(
        'newpost/', 
        views.NewPostView,
        name="newpost"
        ),
    path(
        route='posts/<int:pk>/',
        view=views.PostDetailView, 
        name='postdetail'
    ),  
        
]

users/urls.py
"""Users URLS.s"""

#Django
from django.urls import path

#views
from users import views

urlpatterns = [

    # Management
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    

]

posts/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
    
    category_name = models.CharField(max_length=30,unique=True)


class Post(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    title = models.CharField(max_length=128, null=False)
    date_created = models.DateTimeField(auto_now_add=True)

    content = models.TextField(null=False)

class Tag(models.Model):
    
    tag_name = models.CharField(max_length=30,unique=True)

class Post_Tag(models.Model):

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

users/forms.py
"""User forms."""

#Django
from django import forms

#Models
from django.contrib.auth.models import User

class SignupForm(forms.Form):
    """Sign up form"""

    username = forms.CharField(min_length=4, max_length=50)

    password = forms.CharField(max_length=50 , widget=forms.PasswordInput())
    password_confirmation = forms.CharField(max_length=50 , widget=forms.PasswordInput())

    first_name = forms.CharField(min_length=4, max_length=50)
    last_name = forms.CharField(min_length=4, max_length=50)

    email = forms.CharField(min_length=1, max_length=50,widget=forms.EmailInput())

    def clean_username(self):
        """ Usename must be unique. """
        
        username = self.cleaned_data['username'] #datos que ya limpio python y que los almacena en un dicconario
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """Verify password confirmation match."""

        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

        return data

    def save(self):
        """Create user and profile."""

        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
       

posts/views.py
"""Posts viesw's"""

#Django

from django.views.generic import  TemplateView, ListView, DetailView
from django.contrib.auth import views as auth_views
from django.shortcuts import render
from django.contrib import messages
from django.db import IntegrityError

#Models
from users.models import Post
from users.models import Category
from users.models import Tag
from users.models import Post_Tag

class WelcomeView(TemplateView):
  
    template_name = 'posts/welcome.html'
    

class FeedView(ListView):
    template_name = 'posts/feed.html'
    model = Post
    ordering = ('-created',)
    paginate_by = 3
    context_object_name = 'posts'


    def get_queryset(self):

        queryset = Post.objects.raw(
        """SELECT users_post.id AS id,users_post.title, DATE(users_post.date_created), GROUP_CONCAT(users_tag.tag_name) as Tags, auth_user.id AS User_id
        FROM users_post
	        INNER JOIN users_post_tag ON users_post.id = users_post_tag.post_id
            INNER JOIN users_tag ON users_tag.id = users_post_tag.tag_id
            INNER JOIN auth_user on auth_user.id = users_post.user_id
            GROUP BY users_post.id
            HAVING User_id = {};""".format(self.request.user.id)
        )
        
    
        print(queryset)
    
        return queryset

def PostDetailView(request,pk):
    """Return post detail."""

    queryset = Post.objects.raw(
        """SELECT users_post.id,users_post.title, DATE(users_post.date_created) as Date, GROUP_CONCAT(users_tag.tag_name) as Tags, users_category.category_name as Category, users_post.content as Content
            FROM users_post
                INNER JOIN users_post_tag ON users_post.id = users_post_tag.post_id
                INNER JOIN users_tag ON users_tag.id = users_post_tag.tag_id
                INNER JOIN users_category ON users_category.id = users_post.category_id
            GROUP BY users_post.id
        ;"""
        )
        
    for post in queryset:
        if post.id == pk:
            return render(request, 'posts/postdetail.html',
            {
            'title': post.title,
            'category': post.Category,
            'tags': post.Tags,
            'text': post.Content
            }
            )
            
            break  
    
    return render(request, 'posts/postdetail.html')

    

def NewPostView(request):

    if request.method == 'POST':

        data = request.POST
        user = data['user']
        title = data['title']
        content = data['content']
        category = data['category']
        tag = data['tag']
        
        tag_list = tag.split(',')

        try:
            obj_category = Category(category_name = category)
            obj_category.save()

        except IntegrityError:
            #messages.error(request, "Case ID not found, Try again!")
            print("Ya existe esa Categoria")
       
        for i in tag_list:
            try:
                obj_tag = Tag(tag_name = i)
                obj_tag.save()
            
            except IntegrityError:
                print("Ya existe ese Tag")

        obj_category_id = Category.objects.get(category_name = category).id
        
        tag_id_list = []
        for i in tag_list:
            obj_tag_id = Tag.objects.get(tag_name = i).id
            tag_id_list.append(obj_tag_id)
        
        obj_post = Post(
            title = title,
            content = content,
            category_id = obj_category_id,
            user_id = user
        )
        obj_post.save()

        obj_post_id = Post.objects.get(title= title).id

        for i in tag_id_list:
            obj_users_post_tag = Post_Tag(
                post_id = obj_post_id,
                tag_id = int(i)
            )

            obj_users_post_tag.save()


    return render(request, 'posts/newpost.html')

users/views.py
"""Users URLS.s"""

#Django
from django.shortcuts import render
from django.views.generic import  FormView
from django.urls import reverse, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin

#Models
from users.forms import SignupForm
from django.contrib.auth.models import User

class SignupView(FormView):
    """Users sign up view"""

    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Save form data"""
        form.save()
        return super().form_valid(form)

class LoginView(auth_views.LoginView):
    """Login view"""

    template_name = 'users/login.html'

class LogoutView(LoginRequiredMixin,auth_views.LogoutView):
    """Logout view."""

    template_name = 'users/logged_out.html'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main2.css' %}" />
   
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
 
</head>
<body>

    

    <div class="container mt-5">
        {% block container %}

        {% endblock%}
    </div>

<div class="footer">
    <p>Copyright © 2020 CQQ</p>
</div>

</body>


</html>

templates/nav.html
<nav class="navbar " id="main-navbar">
    <a class="navbar-brand text-dark"  href="{% url "posts:feed"  %}">Your personal blog.</a>
</nav>

templates/navwelcome.html
<nav class="navbar " id="main-navbar">
    <a class="navbar-brand text-dark"  href="{% url "posts:welcome"  %}">Your personal blog.</a>
    <form class="form-inline my-2 my-lg-0">
      <button class="btn btn-sm btn-outline-secondary mr-sm-2" type="button" onclick="window.location.href='{% url "users:signup"  %}'">Star your blog!</button>
      <button class="btn btn-sm btn-outline-secondary my-2 my-sm-0" type="button" onclick="window.location.href='{% url "users:login"  %}'">Login</button>
    </form>
</nav>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" >
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

templates/posts/feed.html
{% extends "base.html" %}

{% block head_content %}
    <title>Feed</title>
    {% include "nav.html" %}
{% endblock %}

{% block container %}

<h1>Your posts...</h1>

{% for post in posts %}
    <div class="card">
        <div class="card-header">
                Post: {{ post.date_created}}
        </div>
        <div class="card-body">
            <h5 class="card-title">{{post.title}}</h5>
            <p class="card-text">Tags: {{post.Tags}}</p>
            <a href="{% url "posts:postdetail" post.id %}" class="btn btn-secondary">Visit post</a>
        </div>
    </div>
{% endfor %}

    <div class="fab"> 
        <a a class="text-dark" style="text-decoration: none;" href="{% url "posts:newpost"  %}">+</a>
    </div>


{% include "pagination.html" %}   
{% endblock %}

templates/posts/newpost.html
{% extends "base.html" %}

{% block head_content %}
    <title>New post</title>
    {% include "nav.html" %}
{% endblock %}

{% block container %}

<h1>New Post!</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <input type="hidden" name="user" value="{{ user.pk }}" />
    
    <div class="form-group">
        <input
            class="form-control"
            type="text"
            name="title"
            placeholder="Title"
            required
        >
    </div>

    <div class="form-group">
        <label for="exampleFormControlTextarea1">Content:</label>
        <textarea 
            class="form-control" 
            id="exampleFormControlTextarea1" 
            rows="16"
            name ="content"
            required
            ></textarea>
    </div>

    <div class="row">
        <div class="col">
            <input
                class="form-control"
                type="text"
                name="category"
                placeholder="Category"
                required
            >
        </div>
        <div class="col">
            <input
                class="form-control"
                type="text"
                name="tag"
                placeholder="Tags"
                required
            >
        </div>
    </div>
    {% if messages %}       
        {% for message in messages %}
            {% if message.tags == "error" %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endif %}                 
         {% endfor %}           
    {% endif %}

    <button type="submit" class="btn btn-secondary btn-lg mt-5">Post!</button>
    
</form>
    
{% endblock %}

templates/posts/postdetail.html
{% extends "base.html" %}

{% block head_content %}
    <title>Post</title>
    {% include "nav.html" %}
{% endblock %}

{% block container %}
    
    <div class="card">
        <div class="card-header">
          {{title}}
        </div>
        <div class="card-body">
          <h5 class="card-title">Category: {{category}}</h5>
          <p class="card-text">{{text}}.</p>
          <a href="#" class="btn btn-primary"> {{tags}}</a>
        </div>
      </div>
    
{% endblock %}

templates/posts/welcome.html
{% extends "base.html" %}

{% block head_content %}
    <title>Personal Blog</title>
    {% include "navwelcome.html" %}
    
{% endblock%}

{% block container %}
    
<section class="welcome">
    <div class="welcome-inner">
        <h1>Welcome to your personal blog!</h1>
        <h2>Best place to store your stories, Lets start now!</h2>
        <button class="btn btn-sm btn-outline-secondary my-2 my-sm-0" type="button" onclick="window.location.href='{% url "users:signup"  %}'">Start postig now</button>
    </div>
</section>


{% endblock %}

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main2.css' %}" />

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <h1>Log In!</h1>

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Log In</title>
{% endblock %}

{% block container %}

    {% if form.errors %}
        <p class="alert alert-danger"> 
            Yout username and password did not match please try again
        </p> <!-- clase de bootstrap -->
    {% endif %}
    
    <form method="POST" action="{% url "users:login" %}">
        {% csrf_token %} <!-- Token especial de protección contra ataques que trae django -->

        <div class="form-group"> 
            <input type="text" class=form-control placeholder="Username" name="username"> 
        </div>
        
        <div class="form-group"> 
            <input type="password" class=form-control placeholder="Password" name="password"> 
        </div>

        <button class="btn btn-secondary btn-block mt-5" type="submit">Sign in!</button>
        
    </form>  <!-- el action conecta con la url que llamos login en el archivo de urls, apuntando a la ruta que allá pusimos sin importar la ruta solo guiandose por el name -->

    <p class="mt-4">Don't have an account yet? <a href="{% url "users:signup" %}">Sign up here.</a></p>
{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>CQQ BLog</title>
{% endblock %}

{% block container %}

    {% if form.errors %}
        <p class="alert alert-danger"> 
            Yout username and password did not match please try again
        </p> <!-- clase de bootstrap -->
    {% endif %}

    <form method="POST" action = "{% url "users:signup" %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-block mt-5" type="submit">Sign in!</button>
    </form>

{% endblock %}